apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: db
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: db
    spec:
      containers:
      - image: gcr.io/example-project/k8s-postgres:9.5.2 
        imagePullPolicy: IfNotPresent
        name: db
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: demo-db-01
        name: db-data
